### PR TITLE
Add module exports for components

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
- Export each React component so it can be required like `require ('synfrastructure').Component`

### CODE REVIEW

**Comment by natestormer** [comment]
:star:

**Comment by paulstatezny** [comment]
Almost there; looks like you're removing `libname`, `path`, and `version` from `exports` there.

[Exports and module.exports are nearly the same thing](http://stackoverflow.com/questions/7137397/module-exports-vs-exports-in-node-js)

**Comment by zpchavez** [comment]
Did exporting libname, path, and version come from some documentation or template or something? They don't seem necessary. :interrobang:

**Comment by natestormer** [comment]
:star:

**Comment by zpchavez** [comment]
:+1:

**Pull request merged**
