### PR TITLE
Add tooltip component

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. Tooltips can be specified where they should appear relative to the icon
2. Examples are included
3. It's extensible and SCSS is variablized

### CODE REVIEW

**Comment by kylecesmat** [comment]
:m:

**Comment by kylecesmat** [comment]
Need to reduce complexity of the tooltip component and bring it up to our coding standards

**Comment by kylecesmat** [comment]
:star2:

**Comment by natestormer** [comment]
:hand:

**Comment by natestormer** [comment]
:+1:

**Pull request merged**
